services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /home/gotenks/.config/jellyfin:/config
      - /home/gotenks/.cache/jellyfin:/cache
      - type: bind
        source: /home/gotenks/HDD/Downloads
        target: /media
    restart: 'unless-stopped'
