#!/usr/bin/env bash

# Copyright (C) 2018-20 Akhil Narang
# SPDX-License-Identifier: GPL-3.0-only

# Builds a package from the Arch User Repository
function aur() {
    git clone https://aur.archlinux.org/"${1}"
    cd "${1}" || return
    makepkg -si "${2}"
    cd - || return
    rm -rf "${1}"
}
