#!/usr/bin/env bash

# Copyright (C) 2018-20 Akhil Narang
# Copyright (C) 2020-21 Omkar Chandorkar
# SPDX-License-Identifier: GPL-3.0-only

function upinfo() {
    echo -ne "${green}$(hostname) ${red}uptime is ${cyan} \\t ";uptime | awk /'up/ {print $3,$4,$5,$6,$7,$8,$9,$10,$11}'
}

function onLogin() {
    # Colors
    green='\e[0;32m'
    cyan='\e[0;36m'
    red='\e[0;31m'
    lightgray='\e[0;37m'

    export GIT_PS1_SHOWDIRTYSTATE=1
    export GIT_PS1_SHOWSTASHSTATE=1
    export GIT_PS1_SHOWUNTRACKEDFILES=1
    export GIT_PS1_SHOWUPSTREAM=auto
    export GIT_PS1_SHOWCOLORHINTS=1
    unset PS1
    #PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
    if [[ -f "${HOME}/git-prompt.sh" ]]; then
        source ~/git-prompt.sh
        PS1='| \h (\w)$(__git_ps1 " {%s}") |-> '
    else
        PS1='| \h (\w) |-> '
    fi
    clear
    HOST=$(hostname)
    if [[ ${#HOST} -lt 14 ]]; then
        echo -e "${lightgray}";figlet -c "$(hostname)"
    fi
    echo ""
    echo -ne "${red}Today is:\\t\\t${cyan} $(date)"
    echo ""
    echo -e "${red}Kernel Information: \\t${cyan} $(uname -smr)"
    echo -ne "${cyan}"
    upinfo
    echo ""
    echo -e "Welcome to $(hostname), $(whoami)!"
    echo -e
    fortune
}

function extract () {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjvf $1    ;;
      *.tar.gz)    tar xzvf $1    ;;
      *.tar)       tar xvf $1   ;;
      *.tbz2)      tar xjf $1    ;;
      *.tgz)       tar xzf $1    ;;
      *)           7z x $1       ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

function fastreposync() {
  time schedtool -B -e ionice -n 0 `which repo` sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle -j$(nproc --all) "$@";
}

function gerrit() {
    if [ ! -d ".git" ]; then
        echo -e "Please run this inside a git directory";
    else
        git remote rm gerrit 2>/dev/null;
        [[ -z "${GERRIT_USER}" ]] && export GERRIT_USER=$(git config --get review.gerrit.aospa.co.username);
        if [[ -z "${GERRIT_USER}" ]]; then
            git remote add gerrit $(git remote -v | grep -i "github\.com[:\/]AOSPA" | awk '{print $2}' | uniq | sed -e "s|.*github.com[:\/]AOSPA|ssh://gerrit.aospa.co:29418/AOSPA|");
        else
            git remote add gerrit $(git remote -v | grep -i "github\.com[:\/]AOSPA" | awk '{print $2}' | uniq | sed -e "s|.*github.com[:\/]AOSPA|ssh://${GERRIT_USER}@gerrit.aospa.co:29418/AOSPA|");
        fi
    fi
}

function set_ccache () {
  ccache_path=$(which ccache)
  export USE_CCACHE=1
  export CCACHE_EXEC="$ccache_path"
  export CCACHE_DIR=/home/$USER/.cache/ccache
  $ccache_path -M 10G
  $ccache_path -o compression=true
}
